### PR TITLE
use current Languagetool api

### PR DESCRIPTION
**Pull request by leej3**
as described in:
http://wiki.languagetool.org/public-http-api

### CODE REVIEW

**Comment by leej3** [comment]
Perhaps just documentation of the expected url for the --api-url option would work though...

As in: 

```
java -cp /opt/LanguageTool-4.4/languagetool-server.jar org.languagetool.server.HTTPServer --port 8010
pylanguagetool <input_file> --api-url http://localhost:8010/v2/
```

**Comment by Findus23** [comment]
Hi, 

Thanks for contributing.

Honestly I consider the `/v2/` part of the URL the user has to specify (and the whole project is based on the v2 API you linked to)
So the default URL used is `https://languagetool.org/api/v2/` as you can see here:
https://github.com/Findus23/pyLanguagetool/blob/ad88dcd4a0ae77a0be8c104ebb3bc69d71faed7b/pylanguagetool/__init__.py#L20

And I have configured pylanguagetool to use `https://languagetool.example/v2/`

**Comment by Findus23** [comment]
But you are right that this isn't intuitive, so I added a help to the parameter mentioning that it should always end in `/v2/` (https://github.com/Findus23/pyLanguagetool/commit/4002c042992d04424c53c2c6eb62126e0c449f9c)

**Comment by leej3** [comment]
Agreed. Thanks for the quick response/fix. And for providing the nice utility.

**Pull request closed without merging**
